---
- name: Identify latest ceph:{{ config.data.branch }} build
  shell: curl -s "https://shaman.ceph.com/api/search/?project=ceph&ref={{ config.data.branch }}&flavor=default&status=ready&distros=centos/{{ config.os[site.os].version }}/x86_64&sha1=latest"
  register: get_ceph_shaman

- set_fact:
    ceph_shaman: "{{ get_ceph_shaman.stdout | from_json }}"

- name: Create ceph repo
  yum_repository:
    name: "ceph-{{ config.data.branch }}-{{ ceph_shaman[0].sha1 }}"
    baseurl: "{{ ceph_shaman[0].url }}/x86_64"
    description: "Ceph {{ config.data.branch }} ({{ ceph_shaman[0].sha1 }})"
    enabled: true
    gpgcheck: false
    state: present
