---
- name: Identify latest ceph:{{ config.data.branch }} build
  uri:
    url: "https://shaman.ceph.com/api/search?\
            project=ceph&\
            ref={{ config.data.branch }}&\
            flavor=default&\
            status=ready&\
            distros=centos/{{ config.os[site.os].version }}/x86_64&\
            sha1=latest"
    return_content: true
  register: ceph_shaman

- name: Create ceph repo
  yum_repository:
    name: "ceph-{{ config.data.branch }}-ad94b10d3fb42e8c87599cebf5d87aa390a31336"
    baseurl: "https://2.chacra.ceph.com/r/ceph/wip-anoopcs9-cephfs-proxy-fscrypt-fsync/ad94b10d3fb42e8c87599cebf5d87aa390a31336/centos/9/flavors/default/x86_64"
    description: "Ceph {{ config.data.branch }} (ad94b10d3fb42e8c87599cebf5d87aa390a31336)"
    enabled: true
    gpgcheck: false
    state: present
